amiguetes\PtuitBundle\Entity\Tag:
  type: entity
  table: Tag
  fields:
    id:
      id: true
      type: integer
      unsigned: false
      nullable: false
      generator:
        strategy: IDENTITY
    texto:
      type: string
      length: 12
      fixed: false
      nullable: false
  lifecycleCallbacks: {  }
