amiguetes\PtuitBundle\Entity\UsuarioBloqueado:
  type: entity
  table: Usuario_Bloqueado
  fields:
    id:
      id: true
      type: integer
      unsigned: false
      nullable: false
      generator:
        strategy: IDENTITY
    usuarioid:
      type: integer
      unsigned: false
      nullable: false
      column: usuarioId
    usuarioblockid:
      type: integer
      unsigned: false
      nullable: false
      column: usuarioBlockId
  lifecycleCallbacks: {  }
