amiguetes\PtuitBundle\Entity\Usuario:
  type: entity
  table: Usuario
  fields:
    id:
      id: true
      type: integer
      unsigned: false
      nullable: false
      generator:
        strategy: IDENTITY
    nick:
      type: string
      length: 20
      fixed: false
      nullable: false
    nombre:
      type: string
      length: 50
      fixed: false
      nullable: true
    pass:
      type: string
      length: 160
      fixed: true
      nullable: false
    email:
      type: string
      length: 100
      fixed: false
      nullable: false
    telefono:
      type: string
      length: 20
      fixed: false
      nullable: true
    edad:
      type: integer
      unsigned: false
      nullable: true
    intereses:
      type: text
      nullable: true
    bio:
      type: text
      nullable: true
    localizacion:
      type: string
      length: 200
      fixed: false
      nullable: true
    www:
      type: string
      length: 200
      fixed: false
      nullable: true
    avatar:
      type: string
      length: 45
      fixed: false
      nullable: true
  lifecycleCallbacks: {  }
